### ISSUE TITLE
Thank your for the awesome crate! 

### ISSUE THREAD

**Issue by Boshen** [loyd/top-type-sizes#1]
Just want to say thank you for the awesome work, I was staring at the type sizes output helplessly and then your work appeared! 

Shall we add this crate to https://github.com/nnethercote/perf-book/blob/master/src/type-sizes.md?
Since this is where I learned how to use the `RUSTFLAGS=-Zprint-type-sizes` technique.

**Comment by loyd** [comment]
> Just want to say thank you for the awesome work, I was staring at the type sizes output helplessly and then your work appeared!

Thanks a lot! It's nice to hear that it's useful to someone else. The main purpose of this crate was the `-p` parameter. And it has already helped several times to improve the performance of several places in my async code (in one place +30%). I should probably give more cool examples in the documentation.

> Shall we add this crate to https://github.com/nnethercote/perf-book/blob/master/src/type-sizes.md?

It would be nice, but I'm too modest to make PR there.

**Comment by Boshen** [comment]
I made a PR https://github.com/nnethercote/perf-book/pull/57

FYI I used this to convince swc to change their AST `https://github.com/swc-project/swc/issues/7019`, hence this thank you note :-)

**Comment by Boshen** [comment]
It's in! https://github.com/nnethercote/perf-book/commit/b1c64bcb3f84670a78b39fa66a9ccd4ea2967c48
