### ISSUE TITLE
Show `__awaitee` name

### ISSUE THREAD

**Issue by konstin** [loyd/top-type-sizes#2]
Looking at the output of `top-type-sizes -w -s -h 10 < type-sizes.txt > sizes.txt`, i see a lot of async function whose variant size is dominated by entries such `7904 __awaitee` without further information, so you need to jump through the output file to look up with future has a matching size. Would it be possible to annotate the called future?

**Comment by loyd** [comment]
Sadly, the compiler doesn't provide types of fields (and I haven't found an open issue). However, the size is usually unique for big futures, so if there is exactly one possible candidate, the name can be provided. There are usually several candidates for medium and small futures (<500B). Some heuristics (e.g., `__awaitee` often refers to async fns) can be implemented but can be very misleading in some cases.
